repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-ast
  - id: check-toml
  - id: debug-statements
  - id: no-commit-to-branch
  - id: check-added-large-files
  - id: check-docstring-first
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: ['-x', 'test', '-s', 'B701,B311,B101']
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  hooks:
  - id: commitizen
    stages: [commit-msg]
