"""init_db

Revision ID: 6e945276d216
Revises: 
Create Date: 2024-02-07 16:47:39.962352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e945276d216'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardapios',
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('disciplinas',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('escolas',
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('inep_codigo', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('categoria_administrativa', sa.String(), nullable=True),
    sa.Column('etapa_ensino', sa.String(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('papeis',
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('alunos',
    sa.Column('escola_uuid', sa.UUID(), nullable=True),
    sa.Column('escola_name', sa.String(), nullable=True),
    sa.Column('matricula', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escola_uuid'], ['escolas.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('cardapio_escola',
    sa.Column('escola_uuid', sa.UUID(), nullable=True),
    sa.Column('cardapio_uuid', sa.UUID(), nullable=True),
    sa.Column('cardapio_name', sa.String(), nullable=True),
    sa.Column('cardapio_descricao', sa.String(), nullable=True),
    sa.Column('dia_da_semana', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cardapio_uuid'], ['cardapios.uuid'], ),
    sa.ForeignKeyConstraint(['escola_uuid'], ['escolas.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('relatorios_merendeiras',
    sa.Column('escola_uuid', sa.UUID(), nullable=True),
    sa.Column('escola_name', sa.String(), nullable=True),
    sa.Column('numero_alunos', sa.String(), nullable=True),
    sa.Column('sobra_limpa', sa.String(), nullable=True),
    sa.Column('sobra_suja', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escola_uuid'], ['escolas.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('salas',
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('escola_uuid', sa.UUID(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escola_uuid'], ['escolas.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('usuarios',
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('senha', sa.LargeBinary(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('escola_uuid', sa.UUID(), nullable=True),
    sa.Column('papel_uuid', sa.UUID(), nullable=True),
    sa.Column('escola_name', sa.String(), nullable=True),
    sa.Column('papel_name', sa.String(), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escola_uuid'], ['escolas.uuid'], ),
    sa.ForeignKeyConstraint(['papel_uuid'], ['papeis.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('turmas',
    sa.Column('disciplina', sa.String(), nullable=True),
    sa.Column('sala', sa.UUID(), nullable=True),
    sa.Column('nome_professor', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('horario', sa.Time(), nullable=True),
    sa.Column('ano', sa.Date(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sala'], ['salas.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('aluno_turmas',
    sa.Column('aluno_uuid', sa.UUID(), nullable=True),
    sa.Column('turma_uuid', sa.UUID(), nullable=True),
    sa.Column('turma_name', sa.String(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_uuid'], ['alunos.uuid'], ),
    sa.ForeignKeyConstraint(['turma_uuid'], ['turmas.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('frequencias',
    sa.Column('aluno_turmas_uuid', sa.UUID(), nullable=False),
    sa.Column('chamada', sa.Boolean(), nullable=True),
    sa.Column('data', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_turmas_uuid'], ['aluno_turmas.uuid'], ),
    sa.PrimaryKeyConstraint('aluno_turmas_uuid', 'uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequencias')
    op.drop_table('aluno_turmas')
    op.drop_table('turmas')
    op.drop_table('usuarios')
    op.drop_table('salas')
    op.drop_table('relatorios_merendeiras')
    op.drop_table('cardapio_escola')
    op.drop_table('alunos')
    op.drop_table('papeis')
    op.drop_table('escolas')
    op.drop_table('disciplinas')
    op.drop_table('cardapios')
    # ### end Alembic commands ###
