from .role_schema import *
from .cardapio_escola import *
from .salas import *
from .usuario import *
from .escolas import *
from .turmas import *
from .user_role import *
from .role import *
from .user_role_schema import *
from .user import *
from .login_schema import *
from .aluno_turmas import *
from .papel import *
from .user_schema import *
from .cardapio import *
from .alunos import *
from .frequencias import *
from .disciplinas import *
from .relatorio_merendeiras import *
