from .alunos_model import Alunos
from .aluno_turmas_model import AlunoTurmas
from .cardapio_escola_model import CardapioEscola
from .cardapio_model import Cardapio
from .disciplinas_model import Disciplinas
from .escolas_model import Escolas
from .frequencias_model import Frequencias
from .papel_model import Papel
from .relatorio_merendeiras_model import RelatorioMerendeiras
from .salas_model import Salas
from .turmas_model import Turmas
from .usuario_model import Usuario
